wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers0" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers1" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers2" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers3" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers4" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers5" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers6" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers7"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers8"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers9"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers15"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.DecRegNumberSub1"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.DecRegNumber"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.IncRegNumber"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.IfCurrentRegAccessByLDMSTM"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.out_MEMEnable"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.out_MEMType"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.out_MEMTargetRegister"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.out_LeftReadRegisterEnable"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.out_LeftReadRegisterNumber"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.out_ALULeftFromImm"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.out_IDOwnCanGo"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.in_PipelineRegister_IFID"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_Decoder_ARM.out_ALUMisc"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_MEM.DelayBranchTarget"