wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers0" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers1" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers2" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers3" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers4" "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers5"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_RegisterFile.Registers15"
wave fusion.vwf "tb_system.inst_nnARM.inst_nnARMCore.inst_IF.in_Instruction" "tb_system.inst_nnARM.inst_nnARMCore.inst_IF.in_InstructionWait" "tb_system.inst_nnARM.inst_nnARMCore.inst_IF.out_InstructionAddress"
wave fusion.vwf "tb_system.inst_nnARM.inst_I_Bus2Core.Instruction"
wave fusion.vwf "tb_system.inst_nnARM.inst_I_Bus2Core.wb_ack_i"
wave fusion.vwf "tb_system.inst_nnARM.inst_I_Bus2Core.wb_stb_o"
wave fusion.vwf "tb_system.inst_nnARM.inst_I_Bus2Core.wb_cyc_o"
wave fusion.vwf "tb_system.inst_nnARM.inst_I_Bus2Core.wb_data_i"
wave fusion.vwf "tb_system.inst_nnARM.inst_MemoryController_WB_Bhv.wb_stb_i"
wave fusion.vwf "tb_system.inst_nnARM.inst_MemoryController_WB_Bhv.wb_cyc_i"
wave fusion.vwf "tb_system.inst_nnARM.inst_MemoryController_WB_Bhv.wb_ack_o"
wave fusion.vwf "tb_system.inst_nnARM.inst_MemoryController_WB_Bhv.wb_data_o"
wave fusion.vwf "tb_system.inst_nnARM.D_wb_gnt"
wave fusion.vwf "tb_system.inst_nnARM.I_wb_gnt"
wave fusion.vwf "tb_system.inst_nnARM.D_wb_cyc_o"
wave fusion.vwf "tb_system.inst_nnARM.I_wb_cyc_o"
wave fusion.vwf "tb_system.inst_nnARM.inst_WishBone_Arbiter.wb_cyc_1" "tb_system.inst_nnARM.inst_WishBone_Arbiter.wb_cyc_2"
 