wave fusion.vwf "tb_system.inst_nnARM.inst_IF.PipelineRegister_IFID"
wave fusion.vwf "tb_system.inst_nnARM.inst_IF.ValidInstruction_IFID"
wave fusion.vwf "tb_system.inst_nnARM.inst_ALUShell.ALUType"
wave fusion.vwf "tb_system.inst_nnARM.inst_ALUShell.SimpleALUType"
wave fusion.vwf "tb_system.inst_nnARM.inst_MEM.MEMType"
wave fusion.vwf "tb_system.inst_nnARM.inst_MEM.SimpleMEMType"
wave fusion.vwf "tb_system.inst_nnARM.reset"
wave fusion.vwf "tb_system.inst_nnARM.clock"
wave fusion.vwf "tb_system.inst_nnARM.inst_RegisterFile.Registers0" "tb_system.inst_nnARM.inst_RegisterFile.Registers1" "tb_system.inst_nnARM.inst_RegisterFile.Registers2" "tb_system.inst_nnARM.inst_RegisterFile.Registers3" "tb_system.inst_nnARM.inst_RegisterFile.Registers4" "tb_system.inst_nnARM.inst_RegisterFile.Registers5" "tb_system.inst_nnARM.inst_RegisterFile.Registers6" "tb_system.inst_nnARM.inst_RegisterFile.Registers7"
wave fusion.vwf "tb_system.inst_nnARM.inst_RegisterFile.Registers15"
wave fusion.vwf "tb_system.inst_nnARM.inst_MEM.out_MEMOwnCanGo"
wave fusion.vwf "tb_system.inst_nnARM.inst_ALUShell.ALUOwnCanGo"
wave fusion.vwf "tb_system.inst_nnARM.inst_IF.in_ChangePC"
wave fusion.vwf "tb_system.inst_nnARM.inst_IF.in_MEMChangePC"
wave fusion.vwf "tb_system.inst_nnARM.inst_IF.in_MEMNewPC"
wave fusion.vwf "tb_system.inst_nnARM.inst_IF.in_NewPC"
wave fusion.vwf "tb_system.inst_nnARM.inst_ALUShell.IsBranch"
wave fusion.vwf "tb_system.inst_nnARM.inst_ALUShell.in_ALUMisc"